language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libglib2.0 libglib2.0-dev libjansson4 libjansson-dev
script:
  - ./configure && cd build && make && make CTEST_OUTPUT_ON_FAILURE=1 test

